name: general-search
version: 0.1.0.0
github: "Rick-T/general-search"
license: MIT
author: "Patrick Teubner"
maintainer: "Patrick Teubner"
copyright: "2020 Patrick Teubner"

extra-source-files:
  - README.md
  - ChangeLog.md

description: General interface for creating search algorithms as well as some default implementations. Included are Dijkstra's algorithm, A* and DFS.

dependencies:
  - base >= 4.7 && < 5
  - containers
  - hashable
  - mtl
  - psqueues
  - unordered-containers

data-files:
  - bench/resources/movingai/*/*.map
  - bench/resources/movingai/*/*.map.scen

library:
  source-dirs: src/
  ghc-options:
    - -Wall

tests:
  general-search-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
      - hspec-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - array
      - general-search
      - hspec
      - QuickCheck

benchmarks:
  general-search-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - array
      - astar
      - criterion
      - deepseq
      - general-search
      - monad-dijkstra
      - search-algorithms
